### PR TITLE
Update KF5

### PR DESCRIPTION
**Pull request by tsdgeos**

### CODE REVIEW

**Comment by tsdgeos** [comment]
@aleixpol this is the baloo build failure.

I suspected that was cmake related because it's like as if the moc file isn't being found, but then i've downloaded cmake 3.15.2 and used it on my computer to build baloo and it works, so maybe it isn't.

How hard would be to just try to get a newer cmake in this package?

Any idea how to try to figure out what may be wrong?

Should i try to involve some other KF5 devels?

**Comment by Erick555** [comment]
The full error is:
```
FAILED: bin/baloo_file_extractor 
: && /usr/bin/c++  -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-operator-names -fno-exceptions -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -Wsuggest-override -Wlogical-op -fdiagnostics-color=always -pedantic -Wzero-as-null-pointer-constant  -Wl,--enable-new-dtags -L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed src/file/extractor/CMakeFiles/baloo_file_extractor.dir/baloo_file_extractor_autogen/mocs_compilation.cpp.o src/file/extractor/CMakeFiles/baloo_file_extractor.dir/main.cpp.o src/file/extractor/CMakeFiles/baloo_file_extractor.dir/app.cpp.o src/file/extractor/CMakeFiles/baloo_file_extractor.dir/result.cpp.o src/file/extractor/CMakeFiles/baloo_file_extractor.dir/idlestatemonitor.cpp.o src/file/extractor/CMakeFiles/baloo_file_extractor.dir/__/priority.cpp.o src/file/extractor/CMakeFiles/baloo_file_extractor.dir/__/basicindexingjob.cpp.o src/file/extractor/CMakeFiles/baloo_file_extractor.dir/__/fileindexerconfig.cpp.o src/file/extractor/CMakeFiles/baloo_file_extractor.dir/__/storagedevices.cpp.o src/file/extractor/CMakeFiles/baloo_file_extractor.dir/__/regexpcache.cpp.o src/file/extractor/CMakeFiles/baloo_file_extractor.dir/__/fileexcludefilters.cpp.o src/file/extractor/CMakeFiles/baloo_file_extractor.dir/__/propertydata.cpp.o src/file/extractor/CMakeFiles/baloo_file_extractor.dir/baloodebug.cpp.o src/file/extractor/CMakeFiles/baloo_file_extractor.dir/baloosettings.cpp.o  -o bin/baloo_file_extractor  -Wl,-rpath,/run/build/baloo/bin: /app/lib/libKF5FileMetaData.so.5.69.0 /usr/lib/x86_64-linux-gnu/libKF5ConfigCore.so.5.69.0 /usr/lib/x86_64-linux-gnu/libKF5Solid.so.5.69.0 bin/libKF5BalooEngine.so.5.69.0 /usr/lib/x86_64-linux-gnu/libKF5Crash.so.5.69.0 /usr/lib/x86_64-linux-gnu/libKF5IdleTime.so.5.69.0 /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5.14.2 /usr/lib/x86_64-linux-gnu/libKF5I18n.so.5.69.0 -llmdb /usr/lib/x86_64-linux-gnu/libKF5CoreAddons.so.5.69.0 /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.14.2 /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.14.2 /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.14.2 && :
/usr/lib/gcc/x86_64-unknown-linux-gnu/9.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: src/file/extractor/CMakeFiles/baloo_file_extractor.dir/__/fileindexerconfig.cpp.o: in function `BalooSettings::setDbVersion(int)':
/run/build/baloo/src/file/baloosettings.h:105: undefined reference to `BalooSettings::dbVersionChanged()'
/usr/lib/gcc/x86_64-unknown-linux-gnu/9.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: src/file/extractor/CMakeFiles/baloo_file_extractor.dir/__/fileindexerconfig.cpp.o: in function `BalooSettings::setExcludedFilters(QStringList const&)':
/run/build/baloo/src/file/baloosettings.h:327: undefined reference to `BalooSettings::excludedFiltersChanged()'
/usr/lib/gcc/x86_64-unknown-linux-gnu/9.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: src/file/extractor/CMakeFiles/baloo_file_extractor.dir/__/fileindexerconfig.cpp.o: in function `BalooSettings::setExcludedFiltersVersion(int)':
/run/build/baloo/src/file/baloosettings.h:364: undefined reference to `BalooSettings::excludedFiltersVersionChanged()'
collect2: error: ld returned 1 exit status
```

You may ask fredesktop sdk to update cmake to 3.15.7

BTW: kde runtime already ships [kfilemetdata](https://invent.kde.org/kde/flatpak-kde-runtime/-/blob/qt5.14/org.kde.Sdk.json.in#L652) so shipping it in app is redundant.

**Comment by aleixpol** [comment]
Adding a newer cmake fixed it for me. I don't know why it makes a difference, it's possible that elisa has something wonky on its scripts.
```

    {
        "name": "cmake",
        "buildsystem":"cmake-ninja",
        "cleanup": [
            "/bin",
            "/doc",
            "/share"
        ],
        "sources":[
            {"type":"archive","url":"https://cmake.org/files/v3.17/cmake-3.17.1.tar.gz","sha256":"3aa9114485da39cbd9665a0bfe986894a282d5f0882b1dea960a739496620727"}
        ]
    },
```

I'm not sure this is reason enough to refresh the Sdk's version.

**Comment by Erick555** [comment]
> I'm not sure this is reason enough to refresh the Sdk's version.

Gnome requires bumping `meson` regularly so kde may require bumping `cmake` as well.

**Comment by tsdgeos** [comment]
> Adding a newer cmake fixed it for me. I don't know why it makes a difference, it's possible that elisa has something wonky on its scripts.

FWIW what fails is baloo not elisa

**Comment by tsdgeos** [comment]
For now let's see if we can get it to work here, i'll commit it.

If the SDK gets a newer cmake later we "just" have to remember to remove it from here ^_^

**Comment by Erick555** [comment]
it seems that elisa can't find system libs or is it a bug in runtime?:

```
FAILED: bin/libelisaLib.so.0.1 
: && /usr/bin/c++ -fPIC -O2 -g -pipe -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fno-exceptions -Wall -Wextra -Wcast-align -Wchar-subscripts -Wformat-security -Wno-long-long -Wpointer-arith -Wundef -Wnon-virtual-dtor -Woverloaded-virtual -Werror=return-type -Wvla -Wdate-time -Wsuggest-override -Wlogical-op -fdiagnostics-color=always -pedantic -Wzero-as-null-pointer-constant -O3 -DNDEBUG  -Wl,--no-undefined -Wl,--fatal-warnings -Wl,--enable-new-dtags -L/app/lib -Wl,-z,relro,-z,now -Wl,--as-needed -shared -Wl,-soname,libelisaLib.so.0 -o bin/libelisaLib.so.0.1 src/CMakeFiles/elisaLib.dir/elisaLib_autogen/mocs_compilation.cpp.o src/CMakeFiles/elisaLib.dir/mediaplaylist.cpp.o src/CMakeFiles/elisaLib.dir/mediaplaylistproxymodel.cpp.o src/CMakeFiles/elisaLib.dir/progressindicator.cpp.o src/CMakeFiles/elisaLib.dir/databaseinterface.cpp.o src/CMakeFiles/elisaLib.dir/datatypes.cpp.o src/CMakeFiles/elisaLib.dir/musiclistenersmanager.cpp.o src/CMakeFiles/elisaLib.dir/managemediaplayercontrol.cpp.o src/CMakeFiles/elisaLib.dir/manageheaderbar.cpp.o src/CMakeFiles/elisaLib.dir/manageaudioplayer.cpp.o src/CMakeFiles/elisaLib.dir/trackslistener.cpp.o src/CMakeFiles/elisaLib.dir/elisaapplication.cpp.o src/CMakeFiles/elisaLib.dir/modeldataloader.cpp.o src/CMakeFiles/elisaLib.dir/elisautils.cpp.o src/CMakeFiles/elisaLib.dir/abstractfile/abstractfilelistener.cpp.o src/CMakeFiles/elisaLib.dir/abstractfile/abstractfilelisting.cpp.o src/CMakeFiles/elisaLib.dir/filescanner.cpp.o src/CMakeFiles/elisaLib.dir/filewriter.cpp.o src/CMakeFiles/elisaLib.dir/viewmanager.cpp.o src/CMakeFiles/elisaLib.dir/powermanagementinterface.cpp.o src/CMakeFiles/elisaLib.dir/file/filelistener.cpp.o src/CMakeFiles/elisaLib.dir/file/localfilelisting.cpp.o src/CMakeFiles/elisaLib.dir/models/datamodel.cpp.o src/CMakeFiles/elisaLib.dir/models/abstractmediaproxymodel.cpp.o src/CMakeFiles/elisaLib.dir/models/gridviewproxymodel.cpp.o src/CMakeFiles/elisaLib.dir/models/alltracksproxymodel.cpp.o src/CMakeFiles/elisaLib.dir/models/trackmetadatamodel.cpp.o src/CMakeFiles/elisaLib.dir/models/editabletrackmetadatamodel.cpp.o src/CMakeFiles/elisaLib.dir/models/trackcontextmetadatamodel.cpp.o src/CMakeFiles/elisaLib.dir/models/viewsmodel.cpp.o src/CMakeFiles/elisaLib.dir/localFileConfiguration/elisaconfigurationdialog.cpp.o src/CMakeFiles/elisaLib.dir/indexersManager.cpp.o src/CMakeFiles/elisaLib.dir/databaseLogging.cpp.o src/CMakeFiles/elisaLib.dir/abstractfile/indexercommon.cpp.o src/CMakeFiles/elisaLib.dir/models/modelLogging.cpp.o src/CMakeFiles/elisaLib.dir/playListLogging.cpp.o src/CMakeFiles/elisaLib.dir/vlcLogging.cpp.o src/CMakeFiles/elisaLib.dir/audiowrapper_libvlc.cpp.o src/CMakeFiles/elisaLib.dir/models/filebrowsermodel.cpp.o src/CMakeFiles/elisaLib.dir/models/filebrowserproxymodel.cpp.o src/CMakeFiles/elisaLib.dir/baloo/baloocommon.cpp.o src/CMakeFiles/elisaLib.dir/baloo/localbaloofilelisting.cpp.o src/CMakeFiles/elisaLib.dir/baloo/baloolistener.cpp.o src/CMakeFiles/elisaLib.dir/baloo/baloodetector.cpp.o src/CMakeFiles/elisaLib.dir/baloo/main.cpp.o src/CMakeFiles/elisaLib.dir/baloo/fileindexer.cpp.o src/CMakeFiles/elisaLib.dir/baloo/scheduler.cpp.o src/CMakeFiles/elisaLib.dir/baloowatcherapplicationadaptor.cpp.o src/CMakeFiles/elisaLib.dir/mpris2/mpris2.cpp.o src/CMakeFiles/elisaLib.dir/mpris2/mediaplayer2.cpp.o src/CMakeFiles/elisaLib.dir/mpris2/mediaplayer2player.cpp.o src/CMakeFiles/elisaLib.dir/elisa_settings.cpp.o  /usr/lib/x86_64-linux-gnu/libQt5Multimedia.so.5.14.2  /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5.14.2  /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5.14.2  /usr/lib/x86_64-linux-gnu/libKF5KIOFileWidgets.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5KIOWidgets.so.5.69.0  /app/lib/libKF5Baloo.so.5.69.0  /app/lib/libvlc.so  /usr/lib/x86_64-linux-gnu/libKF5KIOGui.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5KIOCore.so.5.69.0  /usr/lib/x86_64-linux-gnu/libQt5Concurrent.so.5.14.2  /usr/lib/x86_64-linux-gnu/libKF5Service.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5DBusAddons.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5JobWidgets.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5Completion.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5Bookmarks.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5XmlGui.so.5.69.0  /usr/lib/x86_64-linux-gnu/libQt5Network.so.5.14.2  /usr/lib/x86_64-linux-gnu/libKF5WindowSystem.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5ConfigWidgets.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5ConfigGui.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5Auth.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5AuthCore.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5WidgetsAddons.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5Codecs.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5ItemViews.so.5.69.0  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.14.2  /usr/lib/x86_64-linux-gnu/libKF5ConfigCore.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5FileMetaData.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5Solid.so.5.69.0  /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5.14.2  /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.14.2  /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5.14.2  /usr/lib/x86_64-linux-gnu/libKF5I18n.so.5.69.0  /usr/lib/x86_64-linux-gnu/libKF5CoreAddons.so.5.69.0  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.14.2 && :
/usr/lib/gcc/x86_64-unknown-linux-gnu/9.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: src/CMakeFiles/elisaLib.dir/filescanner.cpp.o: in function `FileScannerPrivate::FileScannerPrivate()':
/run/build/elisa/src/filescanner.cpp:47: undefined reference to `KFileMetaData::EmbeddedImageData::EmbeddedImageData()'
/usr/lib/gcc/x86_64-unknown-linux-gnu/9.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: src/CMakeFiles/elisaLib.dir/filescanner.cpp.o: in function `FileScanner::checkEmbeddedCoverImage(QString const&)':
/run/build/elisa/src/filescanner.cpp:280: undefined reference to `KFileMetaData::EmbeddedImageData::imageData(QString const&, QFlags<KFileMetaData::EmbeddedImageData::ImageType>) const'
/usr/lib/gcc/x86_64-unknown-linux-gnu/9.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: src/CMakeFiles/elisaLib.dir/filescanner.cpp.o: in function `FileScannerPrivate::~FileScannerPrivate()':
/run/build/elisa/src/filescanner.cpp:47: undefined reference to `KFileMetaData::EmbeddedImageData::~EmbeddedImageData()'
/usr/lib/gcc/x86_64-unknown-linux-gnu/9.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: src/CMakeFiles/elisaLib.dir/mpris2/mediaplayer2player.cpp.o: in function `MediaPlayer2Player::getMetadataOfCurrentTrack()':
/run/build/elisa/src/mpris2/mediaplayer2player.cpp:426: undefined reference to `KFileMetaData::EmbeddedImageData::EmbeddedImageData()'
/usr/lib/gcc/x86_64-unknown-linux-gnu/9.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /run/build/elisa/src/mpris2/mediaplayer2player.cpp:428: undefined reference to `KFileMetaData::EmbeddedImageData::imageData(QString const&, QFlags<KFileMetaData::EmbeddedImageData::ImageType>) const'
/usr/lib/gcc/x86_64-unknown-linux-gnu/9.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: /run/build/elisa/src/mpris2/mediaplayer2player.cpp:426: undefined reference to `KFileMetaData::EmbeddedImageData::~EmbeddedImageData()'
collect2: error: ld returned 1 exit status
```

**Comment by tsdgeos** [comment]
Yeah it's weird, let's try keeping kfilemetadata in for now

**Comment by tsdgeos** [comment]
I'm mega puzzled, why does it fail in x86_64 but not on aarch64 nor arm?

**Comment by Erick555** [comment]
@tsdgeos note that baloo build succeeded when you removed kfilemetada from app bundle. It failed on elisa build after that.

So the situation is:

1. With bundled kfilemetadata baloo build fails
2. With kfilemetadata from runtime baloo build succeeds but elisa build fails.

This suggests either bug in elisa or in runtime. I think the cmake version doesn't matter here and can be dropped to make it easier to debug.

**Comment by tsdgeos** [comment]
Feel free to open your own  pull request :)

**Comment by Erick555** [comment]
I don't know why it fails. This is question for elisa devs.

**Comment by mgallien** [comment]
> I don't know why it fails. This is question for elisa devs.

I am looking at that.

I am also looking at Baloo to see if I can only build the client library without building the whole framework. The host system should have full Baloo but not the Elisa flatpak.

**Comment by mgallien** [comment]
If I execute this in a context outside of flatpak with a standard build directory, I get this:
` nm --defined src/file/extractor/CMakeFiles/baloo_file_extractor.dir/__/fileindexerconfig.cpp.o | c++filt | grep BalooSettings `

```
0000000000000000 W BalooSettings::setDbVersion(int)
0000000000000000 W BalooSettings::setExcludedFilters(QStringList const&)
0000000000000000 W BalooSettings::setExcludedFiltersVersion(int)
0000000000000000 W BalooSettings::excludedFilters() const
0000000000000000 W BalooSettings::excludedFolders() const
0000000000000000 W BalooSettings::indexingEnabled() const
0000000000000000 W BalooSettings::excludedMimetypes() const
0000000000000000 W BalooSettings::onlyBasicIndexing() const
0000000000000000 W BalooSettings::indexHiddenFolders() const
0000000000000000 W BalooSettings::isDbVersionImmutable() const
0000000000000000 W BalooSettings::excludedFiltersVersion() const
0000000000000000 W BalooSettings::isExcludedFiltersImmutable() const
0000000000000000 W BalooSettings::isExcludedFiltersVersionImmutable() const
0000000000000000 W BalooSettings::folders() const
0000000000000000 W BalooSettings::dbVersion() const
0000000000000000 W BalooSettings::isDbVersionImmutable() const::{lambda()#1}::operator()() const
0000000000000000 W BalooSettings::isExcludedFiltersImmutable() const::{lambda()#1}::operator()() const
0000000000000000 W BalooSettings::isExcludedFiltersVersionImmutable() const::{lambda()#1}::operator()() const
0000000000000000 u BalooSettings::isDbVersionImmutable() const::{lambda()#1}::operator()() const::qstring_literal
0000000000000000 u BalooSettings::isExcludedFiltersImmutable() const::{lambda()#1}::operator()() const::qstring_literal
0000000000000000 u BalooSettings::isExcludedFiltersVersionImmutable() const::{lambda()#1}::operator()() const::qstring_literal
```

In a flatpak context:
```
0000000000000000 u BalooSettings::isDbVersionImmutable() const::{lambda()#1}::operator()() const::qstring_literal
0000000000000000 u BalooSettings::isExcludedFiltersImmutable() const::{lambda()#1}::operator()() const::qstring_literal
0000000000000000 u BalooSettings::isExcludedFiltersVersionImmutable() const::{lambda()#1}::operator()() const::qstring_literal
```
The weak symbols are missing.

@tsdgeos  Do you have an idea what compilation option may do this ?

I will keep looking at that to understand what is the root cause.

**Comment by tsdgeos** [comment]
This is mega weird because this actually succeeds in my computer.

Can anyone else confirm it works for them?

**Comment by aleixpol** [comment]
It did compile for me when I commented. It compiled all the way.

**Comment by mgallien** [comment]
> This is mega weird because this actually succeeds in my computer.
> 
> Can anyone else confirm it works for them?

It works now for me with the latest commit. Not sure why the switch to cmake+make can solve that build failure.

**Comment by tsdgeos** [comment]
@aleixpol any idea who in the flathub side can we ask about this? it's weird when it compiles locally and not on the server supposedly we're using the exact same stuff, no?

**Comment by aleixpol** [comment]
In general, #flatpak has been very helpful.
There's also the flatpak@lists.freedesktop.org mailing list.

**Comment by barthalion** [comment]
For those of you who can build it locally, can you check what runtime and SDK commits you have installed?

```
bpiotrowski@cncf-x86-1:~/org.kde.elisa$ flatpak info org.kde.Sdk//5.14

KDE Software Development Kit - Tools and headers for developing applications
using the KDE application platform

          ID: org.kde.Sdk
         Ref: runtime/org.kde.Sdk/x86_64/5.14
        Arch: x86_64
      Branch: 5.14
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 2.2 GB

      Commit: d994bb8f4e0d20bccd5b4dacb350c63573ccb2431fbb7e1336172e7f48938887
      Parent: 014bcb6da0a15f590eb3089d06ff7ccd819752d5871e0a1bc7cd16530def3e7a
     Subject: build of org.kde.Sdk, Thu Apr 23 11:49:40 UTC 2020 (ad56284f52fedca22c0ba56a16bce7764bb82a09)
        Date: 2020-04-23 20:14:50 +0000
bpiotrowski@cncf-x86-1:~/org.kde.elisa$ flatpak info org.kde.Platform//5.14

KDE Application Platform - Shared libraries used by KDE applications

          ID: org.kde.Platform
         Ref: runtime/org.kde.Platform/x86_64/5.14
        Arch: x86_64
      Branch: 5.14
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 925.6 MB

      Commit: 97b1b0170a43cb00b175d5dd9ebc06d853dd08a5e490ee73b64a8054dcf19aa2
      Parent: a3cb0a919616a6740699760155b9f869735526618230e38e41cbbf9585051637
     Subject: build of org.kde.Sdk, Thu Apr 23 11:49:40 UTC 2020 (ad56284f52fedca22c0ba56a16bce7764bb82a09)
        Date: 2020-04-23 20:13:55 +0000

```

I can actually reproduce the failure locally with these two.

**Comment by barthalion** [comment]
Builds fine with previous runtime/sdk versions though:

```
flatpak update --commit=a3cb0a919616a6740699760155b9f869735526618230e38e41cbbf9585051637 org.kde.Platform//5.14
flatpak update --commit=014bcb6da0a15f590eb3089d06ff7ccd819752d5871e0a1bc7cd16530def3e7a org.kde.Sdk//5.14
```

**Comment by aleixpol** [comment]
I just built this branch successfully against:
```

KDE Software Development Kit - Tools and headers for developing applications
using the KDE application platform

          ID: org.kde.Sdk
         Ref: runtime/org.kde.Sdk/x86_64/5.14
        Arch: x86_64
      Branch: 5.14
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 2,2 GB

      Commit: d994bb8f4e0d20bccd5b4dacb350c63573ccb2431fbb7e1336172e7f48938887
      Parent: 014bcb6da0a15f590eb3089d06ff7ccd819752d5871e0a1bc7cd16530def3e7a
     Subject: build of org.kde.Sdk, Thu Apr 23 11:49:40 UTC 2020 (ad56284f52fedca22c0ba56a16bce7764bb82a09)
        Date: 2020-04-23 20:14:50 +0000
```

I removed .flatpak-builder just in case.

I used the following line:
`flatpak-builder --force-clean --arch=x86_64 --ccache --repo=repo app org.kde.elisa.json`

**Comment by tsdgeos** [comment]
Same as @aleixpol works here with 

```
tsdgeos@xps:~:$ flatpak info org.kde.Sdk//5.14

KDE Software Development Kit - Tools and headers for developing applications
using the KDE application platform

          ID: org.kde.Sdk
         Ref: runtime/org.kde.Sdk/x86_64/5.14
        Arch: x86_64
      Branch: 5.14
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 2,2 GB

      Commit: d994bb8f4e0d20bccd5b4dacb350c63573ccb2431fbb7e1336172e7f48938887
      Parent: 014bcb6da0a15f590eb3089d06ff7ccd819752d5871e0a1bc7cd16530def3e7a
     Subject: build of org.kde.Sdk, Thu Apr 23 11:49:40 UTC 2020 (ad56284f52fedca22c0ba56a16bce7764bb82a09)
        Date: 2020-04-23 20:14:50 +0000
tsdgeos@xps:~:$ flatpak info org.kde.Platform//5.14

KDE Application Platform - Shared libraries used by KDE applications

          ID: org.kde.Platform
         Ref: runtime/org.kde.Platform/x86_64/5.14
        Arch: x86_64
      Branch: 5.14
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 925,6 MB

      Commit: 97b1b0170a43cb00b175d5dd9ebc06d853dd08a5e490ee73b64a8054dcf19aa2
      Parent: a3cb0a919616a6740699760155b9f869735526618230e38e41cbbf9585051637
     Subject: build of org.kde.Sdk, Thu Apr 23 11:49:40 UTC 2020 (ad56284f52fedca22c0ba56a16bce7764bb82a09)
        Date: 2020-04-23 20:13:55 +0000
tsdgeos@xps:~:$ 

```

**Comment by mgallien** [comment]
I reproduce the build failure with the same version than @barthalion .

**Comment by mgallien** [comment]
I also get a build failure if I remove KFileMetaData only or if I also upgrade Baloo.

**Comment by nedrichards** [comment]
Builds fine locally for me on Endless 3.8.1

```
nick@nedr-yoga:~/Projects/org.kde.elisa$ flatpak info org.kde.Sdk//5.14

KDE Software Development Kit - Tools and headers for developing applications
using the KDE application platform

          ID: org.kde.Sdk
         Ref: runtime/org.kde.Sdk/x86_64/5.14
        Arch: x86_64
      Branch: 5.14
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 2.2 GB

      Commit: d994bb8f4e0d20bccd5b4dacb350c63573ccb2431fbb7e1336172e7f48938887
      Parent: 014bcb6da0a15f590eb3089d06ff7ccd819752d5871e0a1bc7cd16530def3e7a
     Subject: build of org.kde.Sdk, Thu Apr 23 11:49:40 UTC 2020 (ad56284f52fedca22c0ba56a16bce7764bb82a09)
        Date: 2020-04-23 20:14:50 +0000

nick@nedr-yoga:~/Projects/org.kde.elisa$ flatpak info org.kde.Platform//5.14

KDE Application Platform - Shared libraries used by KDE applications

          ID: org.kde.Platform
         Ref: runtime/org.kde.Platform/x86_64/5.14
        Arch: x86_64
      Branch: 5.14
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 925.6 MB

      Commit: 97b1b0170a43cb00b175d5dd9ebc06d853dd08a5e490ee73b64a8054dcf19aa2
      Parent: a3cb0a919616a6740699760155b9f869735526618230e38e41cbbf9585051637
     Subject: build of org.kde.Sdk, Thu Apr 23 11:49:40 UTC 2020 (ad56284f52fedca22c0ba56a16bce7764bb82a09)
        Date: 2020-04-23 20:13:55 +0000

```

**Comment by mgallien** [comment]
@tsdgeos The update of Sdk and platform that has been available today has fixed the build for me. Let's try again.

**Comment by mgallien** [comment]
bot, build

**Comment by mgallien** [comment]
There is a fix for the build failure of Baloo. @eszlari has a fork of Dolphin flathub build that switch to out of source build for Baloo. I have checked and it is building fine on flathub. Thanks a lot for the fix !

@tsdgeos Do you want me to push the fix on your branch ?

**Comment by tsdgeos** [comment]
Well it still doesn't work locally for me, i'd suggest you just propose a new Pull Request and merge it if you can make it work and we close this one

**Comment by mgallien** [comment]
> Well it still doesn't work locally for me, i'd suggest you just propose a new Pull Request and merge it if you can make it work and we close this one

Thanks, I have done that. You can close this one.

**Pull request closed without merging**
