### PR TITLE
KDE KF6 update

### PR DESCRIPTION
**Pull request by travier**
Launches but I can not play radios. Not tried music yet.

### CODE REVIEW

**Comment by travier** [comment]
bot, build

**Comment by travier** [comment]
bot, build

**Comment by travier** [comment]
Hum, why do you think it needs RW access to home?

**Comment by travier** [comment]
I was from https://github.com/flathub/org.kde.elisa/issues/3

**Comment by mgallien** [comment]
> > Hum, why do you think it needs RW access to home?
> 
> I guess we could do `--filesystem=xdg-music` and have it RW so we can edit/tag the music, but then let users add other folders using the portal. I just need to sort out `git` since I have just installed Fedora Kinoite 🎉

last time I had time to work on this, I am not sure adding a folder via portal was working with Elisa music indexer
I can try again if that would help

**Comment by Justinzobel** [comment]
What's the status on this merge?

**Comment by travier** [comment]
> last time I had time to work on this, I am not sure adding a folder via portal was working with Elisa music indexer
> I can try again if that would help

You can not do that as the access granted this way is temporary and will be "removed" (not be granted again) the next time the app is restarted.

**Comment by travier** [comment]
> What's the status on this merge?

Updated it again. Let's keep the discussion about host/music access for a later PR. What's needed for this one is to verify that most functionalities work properly. I don't have music files at hand to try.

**Comment by travier** [comment]
Issues found so far, maybe not due to this update:
- Really bad audio quality from some radios
- Tries to setup an inotify watch in a loop and never stops:
```
inotify_add_watch(/var/home/user) failed: (Permission denied)
```

**Comment by Erick555** [comment]
> You can not do that as the access granted this way is temporary and will be "removed" (not be granted again) the next time the app is restarted.
> 
> This is essentially #2

Portal access is surely persistent unless elisa does something very special or you remove permissions database manually. In general portals do support giving access to whole folder for years so #2 is obsolete.

**Comment by travier** [comment]
bot, build

**Comment by aidzmtsk** [comment]
Heyo, what's the status of this PR?

**Comment by mgallien** [comment]
bot, build

**Comment by travier** [comment]
I've split the access change out of this PR so that we can move forward with the KF6 update first and then see that after: https://github.com/flathub/org.kde.elisa/pull/127#issuecomment-2056648558

**Comment by mgallien** [comment]
@travier as far as I know the releases of Elisa using Qt6 no longer depend on baloo
not sure you would want to remove it now

**Comment by travier** [comment]
Thanks, pushed that change as well.

**Comment by mgallien** [comment]
@travier I did not do a local build but it really looks like the release of vlc is being built against an incompatible release of taglib
did you already looked into this ?

**Comment by mgallien** [comment]
see this https://invent.kde.org/packaging/flatpak-kde-runtime/-/blame/qt6.7/org.kde.Sdk.json.in?ref_type=heads#L1344
not sure the current libvlc release that we build is compatible

**Comment by Erick555** [comment]
Arch has patch for that (for vlc): https://gitlab.archlinux.org/archlinux/packaging/packages/vlc/-/blob/main/taglib-2.patch

**Comment by mgallien** [comment]
thanks @Erick555 
@travier can you add the patch ?
I also confirm that 3.0.21 release of vlc is also failing to build against taglib-2.0.1

**Comment by mgallien** [comment]
works nicely
thanks @travier

**Comment by travier** [comment]
It kinda works for me but it crashes all the time, when indexing, playing music, etc.

In the logs I get lots of:
```
qrc:/qt/qml/org/kde/elisa/qml/DataTrackView.qml:81:9: Unable to assign QString to int
```

and it looks like it's trying to index my whole system:
```
inotify_add_watch(/sysroot/ostree/repo/extensions/rpmostree/private) failed: (Permission denied)
...
inotify_add_watch(/run/host/etc/polkit-1/rules.d) failed: (Permission denied)
```

**Comment by travier** [comment]
Looks like the stutter issue is https://bugs.kde.org/show_bug.cgi?id=443184

**Comment by mgallien** [comment]
my config is set to index a specific folder
I tested indexing from scratch but did not tested an empty configuration

**Comment by travier** [comment]
OK, this one has been waiting for a while. Let's start with that and we can iterate.

**Pull request merged**
