### PR TITLE
Drop force Breeze icon theme patch

### LINKED ISSUE #54: Flatpak Elisa uses wrong icons in dark mode
bad-icons

STEPS TO REPRODUCE:
1. Click Hamburger menu
2. Select colour scheme
3. Select Breeze Dark
4. Look at icons

EXPECTED RESULT:
Icons should be the dark theme icons

OBSERVED RESULT:
Icons are the light theme icons and blend in with the background

### PR DESCRIPTION
**Pull request by vulongm**
Resolves #54, icons properly follow the selected color scheme with the patch removed.

### CODE REVIEW

**Comment by vulongm** [comment]
@travier Could you look at this patch? Seems to be working on my end so far.

**Comment by travier** [comment]
CC @tsdgeos as I don't have the context

**Comment by travier** [comment]
From https://github.com/flathub/org.kde.elisa/pull/38

**Comment by travier** [comment]
Seems reasonable considering https://github.com/flathub/org.kde.elisa/issues/54#issuecomment-1009126753

**Comment by travier** [comment]
Worked for me as far as I could see so merging.

**Pull request merged**
