### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by Erick555**
See commit description for details

### CODE REVIEW

**Comment by Erick555** [comment]
@mgallien @tsdgeos ready to merge

**Comment by tsdgeos** [comment]
I don't feel particularly happy about that vlc cache patch. 

Have you brought this upstream iether to VLC or to flatpak devels?

**Comment by Erick555** [comment]
@tsdgeos this patch is from @MatMaul who is [vlc upstream contributor](https://www.videolan.org/videolan/team/) and flatpak vlc maintainer. I don't think we can do better than that.

**Comment by mgallien** [comment]
@Erick555 Thanks for the clean up.

@tsdgeos VLC flatpak also has the same patch. To me, its look like a good idea to use it. What do you think ?

@Erick555 We should keep an eye on VLC flatpak packaging and drop this patch once they no longer use it.

**Comment by tsdgeos** [comment]
Sure, let's have it i guess, it's just sad that we need special flatpak patches, ideally all that would be included upstream

**Comment by Erick555** [comment]
For my understanding this is patch for flatpak specific issue that may be unwanted elsewhere. That saying there is [patch for elisa itself in this repo](https://github.com/flathub/org.kde.elisa/blob/master/0001-force-Breeze-icon-theme.patch)

**Comment by mgallien** [comment]
The patch in Elisa is due to my lazyness to fix issues when not using Breeze icon theme. That would require a not trivial effort to make sure that it is usable. It has been added during review when being integrated into Flathub.

**Pull request merged**
